version: '3.8'

networks:
  app_network:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    restart: always
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=Vxk#92R!d7E^nM4yPlW9g!8f*Ko@1HnB
      - DATABASE_URL=postgresql://orangetool_task_user:sGX26XKf624WHZpA7wSUDujInnNwEq0R@dpg-cvugps9r0fns73833fug-a.oregon-postgres.render.com/orangetool_task
    networks:
      - app_network
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - app_network
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost/api
